import localFont from 'next/font/local'
import './globals.css'

const jostFont = localFont({ src: './Jost-VariableFont_wght.ttf', variable: "--font-jost", display: "swap" })


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={jostFont.className}>
      <main className='w-full max-h-screen overflow-hidden overflow-y-scroll '>
        {children}
      </main>
      </body>
    </html>
  )
}
